In [9]:
import pandas as pd

In [26]:
time_series_df = pd.read_csv("C:/Users/dskcy/UEInfo/AQI_bulletins/data/Processed/AllIndiaBulletinsMaster2025_openrefined.csv")
main_cols = time_series_df.columns

In [31]:
df = pd.read_csv("C:/Users/dskcy/UEInfo/AQI_bulletins/data/Processed/AllIndiaBulletins_Master2025.csv")
columns = df.columns
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.strftime('%b')

In [32]:
df_jul = df[df.month=='Jul'][columns]
df_jul.columns = main_cols
df_jul['date'] = df_jul['date'].dt.strftime('%Y-%m-%d')
df_jul

,date,city,no_stations,aqi_category,aqi,prominent_pollutant
40576,2025-07-01,Nandesari,1,Moderate,147,PM2.5
40577,2025-07-01,Nalbari,1,Good,50,PM2.5
40578,2025-07-01,Naharlagun,1,Good,41,PM10
40579,2025-07-01,Nagpur,4,Good,47,"CO, PM10"
40580,2025-07-01,Muzaffarnagar,1,Satisfactory,53,PM2.5
...,...,...,...,...,...,...
47285,2025-07-31,Gadag,1,Good,44,CO
47286,2025-07-31,Gandhinagar,3,Satisfactory,80,PM10
47287,2025-07-31,Gaya,3,Good,44,"CO, PM2.5"
47288,2025-07-31,Gorakhpur,1,Good,47,O3
47289,2025-07-31,Yadgir,1,Good,42,PM10

In [36]:
pd.concat([time_series_df,df_jul],axis=0).to_csv("C:/Users/dskcy/UEInfo/AQI_bulletins/data/Processed/AQIBulletins202507.csv", index=False)

In [34]:
time_series_df

,date,city,no_stations,aqi_category,aqi,prominent_pollutant
0,2015-05-01,Varanasi,0,Moderate,157,PM10
1,2015-05-01,Kanpur,0,Moderate,175,PM10
2,2015-05-01,Faridabad,0,Moderate,173,PM10
3,2015-05-01,Ahmedabad,0,Moderate,168,PM2.5
4,2015-05-01,Hyderabad,0,Moderate,189,PM2.5
...,...,...,...,...,...,...
428257,2025-06-30,Firozabad,2,Good,22,"PM10, SO2"
428258,2025-06-30,Gandhinagar,2,Satisfactory,52,PM10
428259,2025-06-30,Gangtok,1,Good,18,PM2.5
428260,2025-06-30,Ghaziabad,4,Satisfactory,55,"CO, PM10, PM2.5"
428261,2025-06-30,Vrindavan,1,Satisfactory,51,PM10

In [35]:
434976 - 428262

6714